# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/EECE4632FinalProject/Test_Project_Vivado/test/test.srcs/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_pc_2/dma_axis_ip_example_auto_pc_2.xci
# IP: The module: 'dma_axis_ip_example_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EECE4632FinalProject/Test_Project_Vivado/test/test.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_pc_2/dma_axis_ip_example_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/EECE4632FinalProject/Test_Project_Vivado/test/test.srcs/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_pc_2/dma_axis_ip_example_auto_pc_2.xci
# IP: The module: 'dma_axis_ip_example_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EECE4632FinalProject/Test_Project_Vivado/test/test.gen/sources_1/bd/dma_axis_ip_example/ip/dma_axis_ip_example_auto_pc_2/dma_axis_ip_example_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axis_ip_example_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
