-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity filt is
generic (
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    x_TVALID : IN STD_LOGIC;
    y_TREADY : IN STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    y_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    y_TVALID : OUT STD_LOGIC;
    y_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    y_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    y_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    y_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    y_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    y_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    x_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    x_TREADY : OUT STD_LOGIC;
    x_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    x_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    x_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    x_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    x_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    x_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of filt is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "filt_filt,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.980000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=752,HLS_SYN_LUT=560,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    constant C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    constant C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal regslice_both_y_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_last_fu_169_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal c : STD_LOGIC_VECTOR (63 downto 0);
    signal filt_stream_short_stream_axis_0_lowfreq_shift_reg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal filt_stream_short_stream_axis_0_lowfreq_shift_reg_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal filt_stream_short_stream_axis_0_lowfreq_shift_reg_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal filt_stream_short_stream_axis_0_lowfreq_shift_reg_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal filt_stream_short_stream_axis_0_lowfreq_shift_reg_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal filt_stream_short_stream_axis_0_lowfreq_shift_reg_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal filt_stream_short_stream_axis_0_lowfreq_shift_reg_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal filt_stream_short_stream_axis_0_lowfreq_shift_reg_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal filt_stream_short_stream_axis_0_lowfreq_shift_reg_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal filt_stream_short_stream_axis_0_lowfreq_shift_reg_9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal x_TDATA_blk_n : STD_LOGIC;
    signal tmp_data_reg_335 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_keep_reg_340 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_keep_reg_340_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_strb_reg_345 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_strb_reg_345_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_350 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_user_reg_350_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_355 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_355_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_id_reg_360 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_id_reg_360_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_dest_reg_365 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_dest_reg_365_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal filt_stream_short_stream_axis_0_lowfreq_shift_reg_6_load_reg_370 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_7_fu_203_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_7_reg_376 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_fu_257_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_reg_381 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_2_fu_268_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_2_reg_386 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_8_fu_285_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_8_reg_391 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln43_6_fu_197_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_1_fu_262_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_4_fu_274_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_5_fu_279_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln43_3_fu_325_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_continue_int : STD_LOGIC;
    signal ap_loop_init : STD_LOGIC;
    signal y_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal y_TVALID_int_regslice : STD_LOGIC;
    signal y_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_y_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_data_V_U_apdone_blk : STD_LOGIC;
    signal x_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal x_TVALID_int_regslice : STD_LOGIC;
    signal x_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_x_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal x_TKEEP_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_x_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal x_TSTRB_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_x_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_user_V_U_apdone_blk : STD_LOGIC;
    signal x_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_x_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_last_V_U_apdone_blk : STD_LOGIC;
    signal x_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_x_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_id_V_U_apdone_blk : STD_LOGIC;
    signal x_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_x_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal x_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_x_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component filt_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        c : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component filt_flow_control_loop_pipe_no_ap_cont IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;


    component filt_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    control_s_axi_U : component filt_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        c => c);

    flow_control_loop_pipe_no_ap_cont_U : component filt_flow_control_loop_pipe_no_ap_cont
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_const_logic_1,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_const_logic_0,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_const_logic_0);

    regslice_both_y_V_data_V_U : component filt_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => y_TDATA_int_regslice,
        vld_in => y_TVALID_int_regslice,
        ack_in => y_TREADY_int_regslice,
        data_out => y_TDATA,
        vld_out => regslice_both_y_V_data_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_data_V_U_apdone_blk);

    regslice_both_y_V_keep_V_U : component filt_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_keep_reg_340_pp0_iter1_reg,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_keep_V_U_ack_in_dummy,
        data_out => y_TKEEP,
        vld_out => regslice_both_y_V_keep_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_keep_V_U_apdone_blk);

    regslice_both_y_V_strb_V_U : component filt_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_strb_reg_345_pp0_iter1_reg,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_strb_V_U_ack_in_dummy,
        data_out => y_TSTRB,
        vld_out => regslice_both_y_V_strb_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_strb_V_U_apdone_blk);

    regslice_both_y_V_user_V_U : component filt_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_user_reg_350_pp0_iter1_reg,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_user_V_U_ack_in_dummy,
        data_out => y_TUSER,
        vld_out => regslice_both_y_V_user_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_user_V_U_apdone_blk);

    regslice_both_y_V_last_V_U : component filt_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_last_reg_355_pp0_iter1_reg,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_last_V_U_ack_in_dummy,
        data_out => y_TLAST,
        vld_out => regslice_both_y_V_last_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_last_V_U_apdone_blk);

    regslice_both_y_V_id_V_U : component filt_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_id_reg_360_pp0_iter1_reg,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_id_V_U_ack_in_dummy,
        data_out => y_TID,
        vld_out => regslice_both_y_V_id_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_id_V_U_apdone_blk);

    regslice_both_y_V_dest_V_U : component filt_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_dest_reg_365_pp0_iter1_reg,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_dest_V_U_ack_in_dummy,
        data_out => y_TDEST,
        vld_out => regslice_both_y_V_dest_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_dest_V_U_apdone_blk);

    regslice_both_x_V_data_V_U : component filt_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TDATA,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_data_V_U_ack_in,
        data_out => x_TDATA_int_regslice,
        vld_out => x_TVALID_int_regslice,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_data_V_U_apdone_blk);

    regslice_both_x_V_keep_V_U : component filt_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TKEEP,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_keep_V_U_ack_in,
        data_out => x_TKEEP_int_regslice,
        vld_out => regslice_both_x_V_keep_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_keep_V_U_apdone_blk);

    regslice_both_x_V_strb_V_U : component filt_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TSTRB,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_strb_V_U_ack_in,
        data_out => x_TSTRB_int_regslice,
        vld_out => regslice_both_x_V_strb_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_strb_V_U_apdone_blk);

    regslice_both_x_V_user_V_U : component filt_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TUSER,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_user_V_U_ack_in,
        data_out => x_TUSER_int_regslice,
        vld_out => regslice_both_x_V_user_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_user_V_U_apdone_blk);

    regslice_both_x_V_last_V_U : component filt_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TLAST,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_last_V_U_ack_in,
        data_out => x_TLAST_int_regslice,
        vld_out => regslice_both_x_V_last_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_last_V_U_apdone_blk);

    regslice_both_x_V_id_V_U : component filt_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TID,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_id_V_U_ack_in,
        data_out => x_TID_int_regslice,
        vld_out => regslice_both_x_V_id_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_id_V_U_apdone_blk);

    regslice_both_x_V_dest_V_U : component filt_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TDEST,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_dest_V_U_ack_in,
        data_out => x_TDEST_int_regslice,
        vld_out => regslice_both_x_V_dest_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln43_2_reg_386 <= add_ln43_2_fu_268_p2;
                add_ln43_7_reg_376 <= add_ln43_7_fu_203_p2;
                add_ln43_8_reg_391 <= add_ln43_8_fu_285_p2;
                add_ln43_reg_381 <= add_ln43_fu_257_p2;
                filt_stream_short_stream_axis_0_lowfreq_shift_reg_6_load_reg_370 <= filt_stream_short_stream_axis_0_lowfreq_shift_reg_6;
                tmp_data_reg_335 <= x_TDATA_int_regslice;
                tmp_dest_reg_365 <= x_TDEST_int_regslice;
                tmp_dest_reg_365_pp0_iter1_reg <= tmp_dest_reg_365;
                tmp_id_reg_360 <= x_TID_int_regslice;
                tmp_id_reg_360_pp0_iter1_reg <= tmp_id_reg_360;
                tmp_keep_reg_340 <= x_TKEEP_int_regslice;
                tmp_keep_reg_340_pp0_iter1_reg <= tmp_keep_reg_340;
                tmp_last_reg_355 <= x_TLAST_int_regslice;
                tmp_last_reg_355_pp0_iter1_reg <= tmp_last_reg_355;
                tmp_strb_reg_345 <= x_TSTRB_int_regslice;
                tmp_strb_reg_345_pp0_iter1_reg <= tmp_strb_reg_345;
                tmp_user_reg_350 <= x_TUSER_int_regslice;
                tmp_user_reg_350_pp0_iter1_reg <= tmp_user_reg_350;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                filt_stream_short_stream_axis_0_lowfreq_shift_reg <= filt_stream_short_stream_axis_0_lowfreq_shift_reg_1;
                filt_stream_short_stream_axis_0_lowfreq_shift_reg_1 <= filt_stream_short_stream_axis_0_lowfreq_shift_reg_2;
                filt_stream_short_stream_axis_0_lowfreq_shift_reg_2 <= filt_stream_short_stream_axis_0_lowfreq_shift_reg_3;
                filt_stream_short_stream_axis_0_lowfreq_shift_reg_3 <= filt_stream_short_stream_axis_0_lowfreq_shift_reg_4;
                filt_stream_short_stream_axis_0_lowfreq_shift_reg_4 <= filt_stream_short_stream_axis_0_lowfreq_shift_reg_5;
                filt_stream_short_stream_axis_0_lowfreq_shift_reg_5 <= filt_stream_short_stream_axis_0_lowfreq_shift_reg_6_load_reg_370;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                filt_stream_short_stream_axis_0_lowfreq_shift_reg_6 <= filt_stream_short_stream_axis_0_lowfreq_shift_reg_7;
                filt_stream_short_stream_axis_0_lowfreq_shift_reg_7 <= filt_stream_short_stream_axis_0_lowfreq_shift_reg_8;
                filt_stream_short_stream_axis_0_lowfreq_shift_reg_8 <= filt_stream_short_stream_axis_0_lowfreq_shift_reg_9;
                filt_stream_short_stream_axis_0_lowfreq_shift_reg_9 <= x_TDATA_int_regslice;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln43_1_fu_262_p2 <= std_logic_vector(unsigned(filt_stream_short_stream_axis_0_lowfreq_shift_reg_2) + unsigned(filt_stream_short_stream_axis_0_lowfreq_shift_reg_3));
    add_ln43_2_fu_268_p2 <= std_logic_vector(unsigned(add_ln43_1_fu_262_p2) + unsigned(filt_stream_short_stream_axis_0_lowfreq_shift_reg_1));
    add_ln43_3_fu_325_p2 <= std_logic_vector(unsigned(add_ln43_2_reg_386) + unsigned(add_ln43_reg_381));
    add_ln43_4_fu_274_p2 <= std_logic_vector(unsigned(filt_stream_short_stream_axis_0_lowfreq_shift_reg_5) + unsigned(filt_stream_short_stream_axis_0_lowfreq_shift_reg_6_load_reg_370));
    add_ln43_5_fu_279_p2 <= std_logic_vector(unsigned(add_ln43_4_fu_274_p2) + unsigned(filt_stream_short_stream_axis_0_lowfreq_shift_reg_4));
    add_ln43_6_fu_197_p2 <= std_logic_vector(unsigned(filt_stream_short_stream_axis_0_lowfreq_shift_reg_8) + unsigned(filt_stream_short_stream_axis_0_lowfreq_shift_reg_9));
    add_ln43_7_fu_203_p2 <= std_logic_vector(unsigned(add_ln43_6_fu_197_p2) + unsigned(filt_stream_short_stream_axis_0_lowfreq_shift_reg_7));
    add_ln43_8_fu_285_p2 <= std_logic_vector(unsigned(add_ln43_7_reg_376) + unsigned(add_ln43_5_fu_279_p2));
    add_ln43_fu_257_p2 <= std_logic_vector(unsigned(filt_stream_short_stream_axis_0_lowfreq_shift_reg) + unsigned(tmp_data_reg_335));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_enable_reg_pp0_iter2, regslice_both_y_V_data_V_U_apdone_blk, ap_block_state4_pp0_stage0_iter3, ap_enable_reg_pp0_iter3, ap_loop_exit_ready_pp0_iter3_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (regslice_both_y_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_enable_reg_pp0_iter2, regslice_both_y_V_data_V_U_apdone_blk, ap_block_state4_pp0_stage0_iter3, ap_enable_reg_pp0_iter3, ap_loop_exit_ready_pp0_iter3_reg, y_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (regslice_both_y_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3) or (y_TREADY_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2) or (y_TREADY_int_regslice = ap_const_logic_0))) or ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_enable_reg_pp0_iter2, regslice_both_y_V_data_V_U_apdone_blk, ap_block_state4_pp0_stage0_iter3, ap_enable_reg_pp0_iter3, ap_loop_exit_ready_pp0_iter3_reg, y_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (regslice_both_y_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3) or (y_TREADY_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2) or (y_TREADY_int_regslice = ap_const_logic_0))) or ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(x_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (x_TVALID_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(y_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (y_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(regslice_both_y_V_data_V_U_apdone_blk, y_TREADY_int_regslice)
    begin
                ap_block_state4_pp0_stage0_iter3 <= ((y_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_y_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, tmp_last_fu_169_p1)
    begin
        if (((tmp_last_fu_169_p1 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    m_axi_gmem_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_ARID <= ap_const_lv1_0;
    m_axi_gmem_ARLEN <= ap_const_lv8_0;
    m_axi_gmem_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_ARVALID <= ap_const_logic_0;
    m_axi_gmem_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_AWID <= ap_const_lv1_0;
    m_axi_gmem_AWLEN <= ap_const_lv8_0;
    m_axi_gmem_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_AWVALID <= ap_const_logic_0;
    m_axi_gmem_BREADY <= ap_const_logic_0;
    m_axi_gmem_RREADY <= ap_const_logic_0;
    m_axi_gmem_WDATA <= ap_const_lv32_0;
    m_axi_gmem_WID <= ap_const_lv1_0;
    m_axi_gmem_WLAST <= ap_const_logic_0;
    m_axi_gmem_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_WUSER <= ap_const_lv1_0;
    m_axi_gmem_WVALID <= ap_const_logic_0;
    tmp_last_fu_169_p1 <= x_TLAST_int_regslice;

    x_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_TDATA_blk_n <= x_TVALID_int_regslice;
        else 
            x_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    x_TREADY <= regslice_both_x_V_data_V_U_ack_in;

    x_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_TREADY_int_regslice <= ap_const_logic_1;
        else 
            x_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    y_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, y_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            y_TDATA_blk_n <= y_TREADY_int_regslice;
        else 
            y_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    y_TDATA_int_regslice <= std_logic_vector(unsigned(add_ln43_8_reg_391) + unsigned(add_ln43_3_fu_325_p2));
    y_TVALID <= regslice_both_y_V_data_V_U_vld_out;

    y_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            y_TVALID_int_regslice <= ap_const_logic_1;
        else 
            y_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
