// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="equalizer_equalizer,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=248,HLS_SYN_LUT=460,HLS_VERSION=2022_1}" *)

module equalizer (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        SIGNAL_IN_TDATA,
        SIGNAL_IN_TVALID,
        SIGNAL_IN_TREADY,
        SIGNAL_IN_TKEEP,
        SIGNAL_IN_TSTRB,
        SIGNAL_IN_TUSER,
        SIGNAL_IN_TLAST,
        SIGNAL_IN_TID,
        SIGNAL_IN_TDEST,
        SIGNAL_OUT_TDATA,
        SIGNAL_OUT_TVALID,
        SIGNAL_OUT_TREADY,
        SIGNAL_OUT_TKEEP,
        SIGNAL_OUT_TSTRB,
        SIGNAL_OUT_TUSER,
        SIGNAL_OUT_TLAST,
        SIGNAL_OUT_TID,
        SIGNAL_OUT_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input  [31:0] SIGNAL_IN_TDATA;
input   SIGNAL_IN_TVALID;
output   SIGNAL_IN_TREADY;
input  [3:0] SIGNAL_IN_TKEEP;
input  [3:0] SIGNAL_IN_TSTRB;
input  [1:0] SIGNAL_IN_TUSER;
input  [0:0] SIGNAL_IN_TLAST;
input  [4:0] SIGNAL_IN_TID;
input  [5:0] SIGNAL_IN_TDEST;
output  [31:0] SIGNAL_OUT_TDATA;
output   SIGNAL_OUT_TVALID;
input   SIGNAL_OUT_TREADY;
output  [3:0] SIGNAL_OUT_TKEEP;
output  [3:0] SIGNAL_OUT_TSTRB;
output  [1:0] SIGNAL_OUT_TUSER;
output  [0:0] SIGNAL_OUT_TLAST;
output  [4:0] SIGNAL_OUT_TID;
output  [5:0] SIGNAL_OUT_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] lowfreq_coefs;
wire   [63:0] midfreq_coefs;
wire   [63:0] highfreq_coefs;
reg    SIGNAL_IN_TDATA_blk_n;
reg    SIGNAL_OUT_TDATA_blk_n;
wire    ap_CS_fsm_state2;
reg    ap_block_state1;
wire    regslice_both_SIGNAL_OUT_V_data_V_U_apdone_blk;
reg    ap_block_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    regslice_both_SIGNAL_IN_V_data_V_U_apdone_blk;
wire   [31:0] SIGNAL_IN_TDATA_int_regslice;
wire    SIGNAL_IN_TVALID_int_regslice;
reg    SIGNAL_IN_TREADY_int_regslice;
wire    regslice_both_SIGNAL_IN_V_data_V_U_ack_in;
wire    regslice_both_SIGNAL_IN_V_keep_V_U_apdone_blk;
wire   [3:0] SIGNAL_IN_TKEEP_int_regslice;
wire    regslice_both_SIGNAL_IN_V_keep_V_U_vld_out;
wire    regslice_both_SIGNAL_IN_V_keep_V_U_ack_in;
wire    regslice_both_SIGNAL_IN_V_strb_V_U_apdone_blk;
wire   [3:0] SIGNAL_IN_TSTRB_int_regslice;
wire    regslice_both_SIGNAL_IN_V_strb_V_U_vld_out;
wire    regslice_both_SIGNAL_IN_V_strb_V_U_ack_in;
wire    regslice_both_SIGNAL_IN_V_user_V_U_apdone_blk;
wire   [1:0] SIGNAL_IN_TUSER_int_regslice;
wire    regslice_both_SIGNAL_IN_V_user_V_U_vld_out;
wire    regslice_both_SIGNAL_IN_V_user_V_U_ack_in;
wire    regslice_both_SIGNAL_IN_V_last_V_U_apdone_blk;
wire   [0:0] SIGNAL_IN_TLAST_int_regslice;
wire    regslice_both_SIGNAL_IN_V_last_V_U_vld_out;
wire    regslice_both_SIGNAL_IN_V_last_V_U_ack_in;
wire    regslice_both_SIGNAL_IN_V_id_V_U_apdone_blk;
wire   [4:0] SIGNAL_IN_TID_int_regslice;
wire    regslice_both_SIGNAL_IN_V_id_V_U_vld_out;
wire    regslice_both_SIGNAL_IN_V_id_V_U_ack_in;
wire    regslice_both_SIGNAL_IN_V_dest_V_U_apdone_blk;
wire   [5:0] SIGNAL_IN_TDEST_int_regslice;
wire    regslice_both_SIGNAL_IN_V_dest_V_U_vld_out;
wire    regslice_both_SIGNAL_IN_V_dest_V_U_ack_in;
reg    SIGNAL_OUT_TVALID_int_regslice;
wire    SIGNAL_OUT_TREADY_int_regslice;
wire    regslice_both_SIGNAL_OUT_V_data_V_U_vld_out;
wire    regslice_both_SIGNAL_OUT_V_keep_V_U_apdone_blk;
wire    regslice_both_SIGNAL_OUT_V_keep_V_U_ack_in_dummy;
wire    regslice_both_SIGNAL_OUT_V_keep_V_U_vld_out;
wire    regslice_both_SIGNAL_OUT_V_strb_V_U_apdone_blk;
wire    regslice_both_SIGNAL_OUT_V_strb_V_U_ack_in_dummy;
wire    regslice_both_SIGNAL_OUT_V_strb_V_U_vld_out;
wire    regslice_both_SIGNAL_OUT_V_user_V_U_apdone_blk;
wire    regslice_both_SIGNAL_OUT_V_user_V_U_ack_in_dummy;
wire    regslice_both_SIGNAL_OUT_V_user_V_U_vld_out;
wire    regslice_both_SIGNAL_OUT_V_last_V_U_apdone_blk;
wire    regslice_both_SIGNAL_OUT_V_last_V_U_ack_in_dummy;
wire    regslice_both_SIGNAL_OUT_V_last_V_U_vld_out;
wire    regslice_both_SIGNAL_OUT_V_id_V_U_apdone_blk;
wire    regslice_both_SIGNAL_OUT_V_id_V_U_ack_in_dummy;
wire    regslice_both_SIGNAL_OUT_V_id_V_U_vld_out;
wire    regslice_both_SIGNAL_OUT_V_dest_V_U_apdone_blk;
wire    regslice_both_SIGNAL_OUT_V_dest_V_U_ack_in_dummy;
wire    regslice_both_SIGNAL_OUT_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

equalizer_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .lowfreq_coefs(lowfreq_coefs),
    .midfreq_coefs(midfreq_coefs),
    .highfreq_coefs(highfreq_coefs),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

equalizer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_SIGNAL_IN_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TDATA),
    .vld_in(SIGNAL_IN_TVALID),
    .ack_in(regslice_both_SIGNAL_IN_V_data_V_U_ack_in),
    .data_out(SIGNAL_IN_TDATA_int_regslice),
    .vld_out(SIGNAL_IN_TVALID_int_regslice),
    .ack_out(SIGNAL_IN_TREADY_int_regslice),
    .apdone_blk(regslice_both_SIGNAL_IN_V_data_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_SIGNAL_IN_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TKEEP),
    .vld_in(SIGNAL_IN_TVALID),
    .ack_in(regslice_both_SIGNAL_IN_V_keep_V_U_ack_in),
    .data_out(SIGNAL_IN_TKEEP_int_regslice),
    .vld_out(regslice_both_SIGNAL_IN_V_keep_V_U_vld_out),
    .ack_out(SIGNAL_IN_TREADY_int_regslice),
    .apdone_blk(regslice_both_SIGNAL_IN_V_keep_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_SIGNAL_IN_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TSTRB),
    .vld_in(SIGNAL_IN_TVALID),
    .ack_in(regslice_both_SIGNAL_IN_V_strb_V_U_ack_in),
    .data_out(SIGNAL_IN_TSTRB_int_regslice),
    .vld_out(regslice_both_SIGNAL_IN_V_strb_V_U_vld_out),
    .ack_out(SIGNAL_IN_TREADY_int_regslice),
    .apdone_blk(regslice_both_SIGNAL_IN_V_strb_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 2 ))
regslice_both_SIGNAL_IN_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TUSER),
    .vld_in(SIGNAL_IN_TVALID),
    .ack_in(regslice_both_SIGNAL_IN_V_user_V_U_ack_in),
    .data_out(SIGNAL_IN_TUSER_int_regslice),
    .vld_out(regslice_both_SIGNAL_IN_V_user_V_U_vld_out),
    .ack_out(SIGNAL_IN_TREADY_int_regslice),
    .apdone_blk(regslice_both_SIGNAL_IN_V_user_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_SIGNAL_IN_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TLAST),
    .vld_in(SIGNAL_IN_TVALID),
    .ack_in(regslice_both_SIGNAL_IN_V_last_V_U_ack_in),
    .data_out(SIGNAL_IN_TLAST_int_regslice),
    .vld_out(regslice_both_SIGNAL_IN_V_last_V_U_vld_out),
    .ack_out(SIGNAL_IN_TREADY_int_regslice),
    .apdone_blk(regslice_both_SIGNAL_IN_V_last_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 5 ))
regslice_both_SIGNAL_IN_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TID),
    .vld_in(SIGNAL_IN_TVALID),
    .ack_in(regslice_both_SIGNAL_IN_V_id_V_U_ack_in),
    .data_out(SIGNAL_IN_TID_int_regslice),
    .vld_out(regslice_both_SIGNAL_IN_V_id_V_U_vld_out),
    .ack_out(SIGNAL_IN_TREADY_int_regslice),
    .apdone_blk(regslice_both_SIGNAL_IN_V_id_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 6 ))
regslice_both_SIGNAL_IN_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TDEST),
    .vld_in(SIGNAL_IN_TVALID),
    .ack_in(regslice_both_SIGNAL_IN_V_dest_V_U_ack_in),
    .data_out(SIGNAL_IN_TDEST_int_regslice),
    .vld_out(regslice_both_SIGNAL_IN_V_dest_V_U_vld_out),
    .ack_out(SIGNAL_IN_TREADY_int_regslice),
    .apdone_blk(regslice_both_SIGNAL_IN_V_dest_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 32 ))
regslice_both_SIGNAL_OUT_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TDATA_int_regslice),
    .vld_in(SIGNAL_OUT_TVALID_int_regslice),
    .ack_in(SIGNAL_OUT_TREADY_int_regslice),
    .data_out(SIGNAL_OUT_TDATA),
    .vld_out(regslice_both_SIGNAL_OUT_V_data_V_U_vld_out),
    .ack_out(SIGNAL_OUT_TREADY),
    .apdone_blk(regslice_both_SIGNAL_OUT_V_data_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_SIGNAL_OUT_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TKEEP_int_regslice),
    .vld_in(SIGNAL_OUT_TVALID_int_regslice),
    .ack_in(regslice_both_SIGNAL_OUT_V_keep_V_U_ack_in_dummy),
    .data_out(SIGNAL_OUT_TKEEP),
    .vld_out(regslice_both_SIGNAL_OUT_V_keep_V_U_vld_out),
    .ack_out(SIGNAL_OUT_TREADY),
    .apdone_blk(regslice_both_SIGNAL_OUT_V_keep_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 4 ))
regslice_both_SIGNAL_OUT_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TSTRB_int_regslice),
    .vld_in(SIGNAL_OUT_TVALID_int_regslice),
    .ack_in(regslice_both_SIGNAL_OUT_V_strb_V_U_ack_in_dummy),
    .data_out(SIGNAL_OUT_TSTRB),
    .vld_out(regslice_both_SIGNAL_OUT_V_strb_V_U_vld_out),
    .ack_out(SIGNAL_OUT_TREADY),
    .apdone_blk(regslice_both_SIGNAL_OUT_V_strb_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 2 ))
regslice_both_SIGNAL_OUT_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TUSER_int_regslice),
    .vld_in(SIGNAL_OUT_TVALID_int_regslice),
    .ack_in(regslice_both_SIGNAL_OUT_V_user_V_U_ack_in_dummy),
    .data_out(SIGNAL_OUT_TUSER),
    .vld_out(regslice_both_SIGNAL_OUT_V_user_V_U_vld_out),
    .ack_out(SIGNAL_OUT_TREADY),
    .apdone_blk(regslice_both_SIGNAL_OUT_V_user_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 1 ))
regslice_both_SIGNAL_OUT_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TLAST_int_regslice),
    .vld_in(SIGNAL_OUT_TVALID_int_regslice),
    .ack_in(regslice_both_SIGNAL_OUT_V_last_V_U_ack_in_dummy),
    .data_out(SIGNAL_OUT_TLAST),
    .vld_out(regslice_both_SIGNAL_OUT_V_last_V_U_vld_out),
    .ack_out(SIGNAL_OUT_TREADY),
    .apdone_blk(regslice_both_SIGNAL_OUT_V_last_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 5 ))
regslice_both_SIGNAL_OUT_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TID_int_regslice),
    .vld_in(SIGNAL_OUT_TVALID_int_regslice),
    .ack_in(regslice_both_SIGNAL_OUT_V_id_V_U_ack_in_dummy),
    .data_out(SIGNAL_OUT_TID),
    .vld_out(regslice_both_SIGNAL_OUT_V_id_V_U_vld_out),
    .ack_out(SIGNAL_OUT_TREADY),
    .apdone_blk(regslice_both_SIGNAL_OUT_V_id_V_U_apdone_blk)
);

equalizer_regslice_both #(
    .DataWidth( 6 ))
regslice_both_SIGNAL_OUT_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(SIGNAL_IN_TDEST_int_regslice),
    .vld_in(SIGNAL_OUT_TVALID_int_regslice),
    .ack_in(regslice_both_SIGNAL_OUT_V_dest_V_U_ack_in_dummy),
    .data_out(SIGNAL_OUT_TDEST),
    .vld_out(regslice_both_SIGNAL_OUT_V_dest_V_U_vld_out),
    .ack_out(SIGNAL_OUT_TREADY),
    .apdone_blk(regslice_both_SIGNAL_OUT_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        SIGNAL_IN_TDATA_blk_n = SIGNAL_IN_TVALID_int_regslice;
    end else begin
        SIGNAL_IN_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == SIGNAL_OUT_TREADY_int_regslice) | (1'b0 == SIGNAL_IN_TVALID_int_regslice)) & (1'b1 == ap_CS_fsm_state1))) begin
        SIGNAL_IN_TREADY_int_regslice = 1'b1;
    end else begin
        SIGNAL_IN_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        SIGNAL_OUT_TDATA_blk_n = SIGNAL_OUT_TREADY_int_regslice;
    end else begin
        SIGNAL_OUT_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (1'b0 == SIGNAL_OUT_TREADY_int_regslice) | (1'b0 == SIGNAL_IN_TVALID_int_regslice)) & (1'b1 == ap_CS_fsm_state1))) begin
        SIGNAL_OUT_TVALID_int_regslice = 1'b1;
    end else begin
        SIGNAL_OUT_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (1'b0 == SIGNAL_OUT_TREADY_int_regslice) | (1'b0 == SIGNAL_IN_TVALID_int_regslice))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == SIGNAL_OUT_TREADY_int_regslice) | (regslice_both_SIGNAL_OUT_V_data_V_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == SIGNAL_OUT_TREADY_int_regslice) | (regslice_both_SIGNAL_OUT_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == SIGNAL_OUT_TREADY_int_regslice) | (regslice_both_SIGNAL_OUT_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (1'b0 == SIGNAL_OUT_TREADY_int_regslice) | (1'b0 == SIGNAL_IN_TVALID_int_regslice)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((1'b0 == SIGNAL_OUT_TREADY_int_regslice) | (regslice_both_SIGNAL_OUT_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign SIGNAL_IN_TREADY = regslice_both_SIGNAL_IN_V_data_V_U_ack_in;

assign SIGNAL_OUT_TVALID = regslice_both_SIGNAL_OUT_V_data_V_U_vld_out;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (1'b0 == SIGNAL_OUT_TREADY_int_regslice) | (1'b0 == SIGNAL_IN_TVALID_int_regslice));
end

always @ (*) begin
    ap_block_state2 = ((1'b0 == SIGNAL_OUT_TREADY_int_regslice) | (regslice_both_SIGNAL_OUT_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign m_axi_gmem_ARADDR = 64'd0;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 8'd0;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_ARVALID = 1'b0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 8'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_RREADY = 1'b0;

assign m_axi_gmem_WDATA = 32'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 4'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;


reg find_kernel_block = 0;
// synthesis translate_off
`include "equalizer_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //equalizer

